apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: kube-hellomkes
spec:
  selector:
    matchLabels:
      app: hellomkes-app
  replicas: 1
  template:
    metadata:
      labels:
        app: hellomkes-app
    spec:
      containers:
      - name: hellomkes-app
        image: grahamh/hellomkes-web:2.0
        ports:
        - containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: hellomkes-svc
  labels:
    app: hellomkes-app
spec:
  type: NodePort
  ports:
    - port: 8443
      nodePort: 30090
  selector:
    app: hellomkes-app

